title: IQBench
description: A Benchmark for Evaluating Fluid Intelligence of VLMs
baseurl: "/IQBench"
url: "https://github.com/phuvinhnguyen"

# Google OAuth configuration
google_client_id: "YOUR_GOOGLE_CLIENT_ID"  # Replace with your actual Google Client ID

# Build settings
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "IQBench Team"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore 